"""Pipeline presets: pre-configured generator settings for each method."""

from ...models import ChecklistResponse, WeightedChecklistResponse, CategorizedChecklistResponse

PIPELINE_PRESETS = {
    "tick": {
        "generator_class": "DirectGenerator",
        "template_dir": "generators/tick",
        "template_name": "generate",
        "response_schema": ChecklistResponse,
        "format_name": "checklist",
        "max_items": 8,
        "min_items": 2,
        "temperature": 0.7,
        "default_scorer": {
            "mode": "batch",
            "primary_metric": "pass",
        },
        "description": "Few-shot checklist generation from input text",
        "detail": "Uses a TICK-style prompt to generate yes/no checklist items from the input alone. No reference needed.",
        "requires_reference": False,
    },
    "rocketeval": {
        "generator_class": "DirectGenerator",
        "template_dir": "generators/rocketeval",
        "template_name": "generate",
        "response_schema": ChecklistResponse,
        "format_name": "checklist",
        "max_items": 10,
        "min_items": 1,
        "temperature": 0.7,
        "default_scorer": {
            "mode": "item",
            "use_logprobs": True,
            "primary_metric": "normalized",
            "scorer_prompt": "rocketeval",
        },
        "description": "Confidence-aware checklist from input + reference",
        "detail": "Generates checklist items informed by a reference target, scored via logprobs for calibrated confidence levels.",
        "requires_reference": True,
    },
    "rlcf_direct": {
        "generator_class": "DirectGenerator",
        "template_dir": "generators/rlcf",
        "template_name": "direct",
        "response_schema": WeightedChecklistResponse,
        "format_name": "weighted_checklist",
        "max_items": 7,
        "min_items": 1,
        "temperature": 0.0,
        "default_scorer": {
            "mode": "item",
            "primary_metric": "weighted",
            "scorer_prompt": "rlcf",
        },
        "description": "Weighted criteria from input + reference",
        "detail": "Generates weighted checklist items (0-100 importance) by comparing the input against a reference target.",
        "requires_reference": True,
    },
    "rlcf_candidate": {
        "generator_class": "ContrastiveGenerator",
        "template_dir": "generators/rlcf",
        "template_name": "candidate_based",
        "response_schema": WeightedChecklistResponse,
        "format_name": "weighted_checklist",
        "max_items": 7,
        "min_items": 1,
        "temperature": 0.0,
        "default_scorer": {
            "mode": "item",
            "primary_metric": "weighted",
            "scorer_prompt": "rlcf",
        },
        "description": "Contrastive generation with candidates + reference",
        "detail": "Auto-generates candidate responses, then creates weighted checklist items by contrasting candidates against the reference.",
        "requires_reference": True,
    },
    "rlcf_candidates_only": {
        "generator_class": "ContrastiveGenerator",
        "template_dir": "generators/rlcf",
        "template_name": "candidates_only",
        "response_schema": WeightedChecklistResponse,
        "format_name": "weighted_checklist",
        "max_items": 7,
        "min_items": 1,
        "temperature": 0.0,
        "default_scorer": {
            "mode": "item",
            "primary_metric": "weighted",
            "scorer_prompt": "rlcf",
        },
        "description": "Contrastive generation from candidates only",
        "detail": "Auto-generates candidate responses and derives weighted checklist items by comparing candidates. No reference needed.",
        "requires_reference": False,
    },
    "openrubrics_pairwise": {
        "generator_class": "ContrastiveGenerator",
        "template_dir": "generators/openrubrics",
        "template_name": "pairwise",
        "response_schema": CategorizedChecklistResponse,
        "format_name": "categorized_checklist",
        "max_items": 15,
        "min_items": 1,
        "temperature": 0.0,
        "generate_candidates": False,
        "default_scorer": {"mode": "batch", "primary_metric": "pass"},
        "description": "Contrastive rubric generation from preference pairs (OpenRubrics)",
        "detail": "Generates checklist items by analyzing why a chosen response is superior to a rejected one. Items are categorized as hard_rule (explicit requirements) or principle (implicit qualities).",
        "requires_reference": False,
    },
    "openrubrics_listwise": {
        "generator_class": "ContrastiveGenerator",
        "template_dir": "generators/openrubrics",
        "template_name": "listwise",
        "response_schema": CategorizedChecklistResponse,
        "format_name": "categorized_checklist",
        "max_items": 20,
        "min_items": 1,
        "temperature": 0.0,
        "generate_candidates": False,
        "default_scorer": {"mode": "batch", "primary_metric": "pass"},
        "description": "Contrastive rubric generation from ranked response list (OpenRubrics)",
        "detail": "Generates checklist items by analyzing an ordered list of responses (best to worst). Items are categorized as hard_rule or principle.",
        "requires_reference": False,
    },
}
